#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import { checkSyncStatus } from './check-sync-status.js';
import { validateTransfers } from './compare-transfers.js';
import { validateAccountBalances } from './validate-balances.js';
import { validateDailySnapshots } from './validate-snapshots.js';
import { validateTokenMetadata } from './validate-metadata.js';

const REPORTS_DIR = './reports';

function generateReportFilename() {
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0];
  const timeStr = now.toTimeString().split(' ')[0].replace(/:/g, '-');
  return `validation-report-${dateStr}-${timeStr}.json`;
}

function generateMarkdownReport(report) {
  const { timestamp, syncStatus, validationWindow, transfers, balances, snapshots, metadata, overallStatus, notes } = report;

  const date = new Date(timestamp);
  const dateStr = date.toISOString();

  let md = `# MSQ Tokens Subgraph Validation Report\n\n`;
  md += `**Generated:** ${dateStr}\n\n`;
  md += `**Overall Status:** ${overallStatus === 'PASS' ? '✅ PASS' : '❌ FAIL'}\n\n`;
  md += `---\n\n`;

  // Sync Status
  md += `## Subgraph Sync Status\n\n`;
  md += `- **Current Block:** ${syncStatus.currentBlock.toLocaleString()}\n`;
  md += `- **Block Timestamp:** ${new Date(syncStatus.currentTimestamp * 1000).toISOString()}\n`;
  md += `- **Has Indexing Errors:** ${syncStatus.hasIndexingErrors ? '❌ YES' : '✅ NO'}\n\n`;

  // Validation Window
  md += `## Validation Window\n\n`;
  md += `- **Start Block:** ${validationWindow.startBlock.toLocaleString()}\n`;
  md += `- **End Block:** ${validationWindow.endBlock.toLocaleString()}\n`;
  md += `- **Total Blocks:** ${(validationWindow.endBlock - validationWindow.startBlock).toLocaleString()}\n`;
  md += `- **Time Range:** ${new Date(validationWindow.startTimestamp * 1000).toISOString()} to ${new Date(validationWindow.endTimestamp * 1000).toISOString()}\n\n`;

  // Transfers
  md += `## Transfer Validation\n\n`;
  md += `- **Status:** ${transfers.status}\n`;
  md += `- **Polygonscan Total:** ${transfers.polygonscanTotal}\n`;
  md += `- **Subgraph Total:** ${transfers.subgraphTotal}\n`;
  md += `- **Missing:** ${transfers.missing}\n`;
  md += `- **Extra:** ${transfers.extra}\n`;
  md += `- **Mismatches:** ${transfers.mismatches}\n\n`;

  // Balances
  md += `## Balance Validation\n\n`;
  md += `- **Status:** ${balances.status}\n`;
  md += `- **Accounts Validated:** ${balances.validatedCount} / ${balances.totalAccounts}\n`;
  md += `- **Mismatches:** ${balances.mismatches}\n\n`;

  // Snapshots
  md += `## Snapshot Validation\n\n`;
  md += `- **Status:** ${snapshots.status}\n`;
  md += `- **Snapshots Validated:** ${snapshots.totalSnapshots}\n`;
  md += `- **With Mismatches:** ${snapshots.withMismatches}\n\n`;

  // Metadata
  md += `## Metadata Validation\n\n`;
  md += `- **Status:** ${metadata.status}\n`;
  md += `- **Static Metadata Correct:** ${metadata.staticMetadataCorrect ? '✅ YES' : '❌ NO'}\n`;
  md += `- **Total Supply Matches:** ${metadata.totalSupplyMatches ? '✅ YES' : '⚠️ NO (sync in progress)'}\n`;
  md += `- **Mismatches:** ${metadata.mismatches}\n\n`;

  // Notes
  if (notes && notes.length > 0) {
    md += `## Notes\n\n`;
    notes.forEach(note => {
      md += `- ${note}\n`;
    });
    md += `\n`;
  }

  md += `---\n\n`;
  md += `*Report generated by MSQ Tokens Subgraph Validation Suite*\n`;

  return md;
}

async function runAllValidations() {
  try {
    console.log(chalk.bold.cyan('\n╔══════════════════════════════════════════════════════╗'));
    console.log(chalk.bold.cyan('║   MSQ TOKENS SUBGRAPH VALIDATION SUITE               ║'));
    console.log(chalk.bold.cyan('╚══════════════════════════════════════════════════════╝\n'));

    const startTime = Date.now();

    // Step 1: Check sync status
    console.log(chalk.bold.blue('STEP 1: Checking Sync Status'));
    console.log(chalk.gray('─'.repeat(60)));
    const syncStatus = await checkSyncStatus();
    console.log();

    const validationWindow = {
      startBlock: syncStatus.validationStartBlock,
      endBlock: syncStatus.currentBlock,
      startTimestamp: syncStatus.validationStartTimestamp,
      endTimestamp: syncStatus.currentTimestamp
    };

    // Step 2: Validate Transfers
    console.log(chalk.bold.blue('STEP 2: Validating Transfers'));
    console.log(chalk.gray('─'.repeat(60)));
    const transfersResult = await validateTransfers();
    console.log();

    // Step 3: Validate Balances
    console.log(chalk.bold.blue('STEP 3: Validating Balances'));
    console.log(chalk.gray('─'.repeat(60)));
    const balancesResult = await validateAccountBalances();
    console.log();

    // Step 4: Validate Snapshots
    console.log(chalk.bold.blue('STEP 4: Validating Daily Snapshots'));
    console.log(chalk.gray('─'.repeat(60)));
    const snapshotsResult = await validateDailySnapshots();
    console.log();

    // Step 5: Validate Metadata
    console.log(chalk.bold.blue('STEP 5: Validating Token Metadata'));
    console.log(chalk.gray('─'.repeat(60)));
    const metadataResult = await validateTokenMetadata();
    console.log();

    // Calculate overall status
    const allPassed =
      transfersResult.passed &&
      balancesResult.passed &&
      snapshotsResult.passed &&
      metadataResult.passed;

    const overallStatus = allPassed ? 'PASS' : 'FAIL';

    // Generate report
    const report = {
      timestamp: new Date().toISOString(),
      syncStatus: {
        currentBlock: syncStatus.currentBlock,
        currentTimestamp: syncStatus.currentTimestamp,
        hasIndexingErrors: syncStatus.hasIndexingErrors
      },
      validationWindow,
      transfers: {
        status: transfersResult.passed ? 'PASS' : 'FAIL',
        polygonscanTotal: transfersResult.polygonscanTotal,
        subgraphTotal: transfersResult.subgraphTotal,
        missing: transfersResult.missing,
        extra: transfersResult.extra,
        mismatches: transfersResult.mismatches,
        details: transfersResult.details
      },
      balances: {
        status: balancesResult.passed ? 'PASS' : 'FAIL',
        validatedCount: balancesResult.validatedCount,
        totalAccounts: balancesResult.totalAccounts,
        mismatches: balancesResult.mismatches,
        details: balancesResult.details
      },
      snapshots: {
        status: snapshotsResult.passed ? 'PASS' : 'FAIL',
        totalSnapshots: snapshotsResult.totalSnapshots,
        withMismatches: snapshotsResult.withMismatches,
        details: snapshotsResult.details
      },
      metadata: {
        status: metadataResult.passed ? 'PASS' : 'FAIL',
        staticMetadataCorrect: metadataResult.staticMetadataCorrect,
        totalSupplyMatches: metadataResult.totalSupplyMatches,
        mismatches: metadataResult.mismatches,
        details: metadataResult.details
      },
      overallStatus,
      notes: [
        'Validation performed on recent data (last 24 hours)',
        'Some metrics may be incomplete due to ongoing sync',
        'Historical data validation deferred until 100% sync'
      ]
    };

    // Save JSON report
    if (!fs.existsSync(REPORTS_DIR)) {
      fs.mkdirSync(REPORTS_DIR, { recursive: true });
    }

    const reportFilename = generateReportFilename();
    const reportPath = path.join(REPORTS_DIR, reportFilename);
    fs.writeFileSync(reportPath, JSON.stringify(report, null, 2));

    // Save Markdown report
    const mdFilename = reportFilename.replace('.json', '.md');
    const mdPath = path.join(REPORTS_DIR, mdFilename);
    const mdReport = generateMarkdownReport(report);
    fs.writeFileSync(mdPath, mdReport);

    // Print summary
    const endTime = Date.now();
    const duration = ((endTime - startTime) / 1000).toFixed(2);

    console.log(chalk.bold.cyan('\n╔══════════════════════════════════════════════════════╗'));
    console.log(chalk.bold.cyan('║   VALIDATION SUMMARY                                 ║'));
    console.log(chalk.bold.cyan('╚══════════════════════════════════════════════════════╝\n'));

    console.log(`${chalk.bold('Overall Status:')} ${overallStatus === 'PASS' ? chalk.green.bold('✅ PASS') : chalk.red.bold('❌ FAIL')}\n`);

    console.log(chalk.gray('Individual Results:'));
    console.log(`  Transfers:  ${transfersResult.passed ? chalk.green('✅ PASS') : chalk.red('❌ FAIL')}`);
    console.log(`  Balances:   ${balancesResult.passed ? chalk.green('✅ PASS') : chalk.red('❌ FAIL')}`);
    console.log(`  Snapshots:  ${snapshotsResult.passed ? chalk.green('✅ PASS') : chalk.red('❌ FAIL')}`);
    console.log(`  Metadata:   ${metadataResult.passed ? chalk.green('✅ PASS') : chalk.red('❌ FAIL')}`);

    console.log(chalk.gray(`\nExecution Time: ${duration}s`));
    console.log(chalk.gray(`Reports saved to:`));
    console.log(chalk.yellow(`  JSON: ${reportPath}`));
    console.log(chalk.yellow(`  Markdown: ${mdPath}\n`));

    return report;

  } catch (error) {
    console.error(chalk.red.bold('\n❌ Validation suite failed:'), error.message);
    console.error(error);
    throw error;
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  runAllValidations()
    .then((report) => {
      process.exit(report.overallStatus === 'PASS' ? 0 : 1);
    })
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}

export { runAllValidations };
